name: clean

on:
  pull_request:
    types:
    - closed
    - labeled

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Print reason
        run: |
          echo event.action = ${{ github.event.action }}
          echo PR.labels = ${{ join(github.event.pull_request.labels.*.name, ', ') }}
          echo 'JSON(event.action): ${{ toJSON(github.event.action) }}'
          echo 'JSON(PR.label-names): ${{ toJSON(github.event.pull_request.labels.*.name) }}'
          echo 'JSON(PR.labels): ${{ toJSON(github.event.pull_request.labels) }}'

  triggered:
    if: github.event.action == 'closed' || contains(github.event.pull_request.labels.*.name, 'Stale')
    runs-on: ubuntu-latest
    steps:
    - name: DEBUG
      run: |
        cat << EOF | tee debug-github.txt
        ${{ toJSON(github) }}
        EOF
    - name: Trigger action
      run: echo Triggered by closed or labeled PR!

    - name: Print reason again
      run: |
        echo event.action = ${{ github.event.action }}
        echo PR.labels = ${{ join(github.event.pull_request.labels.*.name, ', ') }}
        echo 'JSON(event.action): ${{ toJSON(github.event.action) }}'
        echo 'JSON(PR.labels): ${{ toJSON(github.event.pull_request.labels) }}'
