name: 'Mark stale PRs'
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.staler_PAT }}
          days-before-pr-stale: 1
          stale-pr-label: stale
          stale-pr-message: This PR is stale because it had no activity for 1 day.
          remove-stale-when-updated: true  # this is default
          days-before-issue-stale: -1
          days-before-close: -1
