name: 'Mark stale PRs'
on:
  schedule:
    - cron: '36 1-23/2 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-pr-stale: 1
          stale-pr-message: 'This PR is stale because it had no activity for 1 day.'
          remove-stale-when-updated: true  # this is default
          days-before-issue-stale: -1
          days-before-close: -1
